### ISSUE TITLE
Additional CSS rules required for the header component to display correctly independent of the other UQDS packages

### ISSUE THREAD

**Issue by uqmchu** [uq-its-ss/design-system#371]
If you copy the HTML markup for the header and load the styles via the NPM package, the header is missing style rules from the @uqds/body and @uqds/form packages. However, it shouldn't need to depend on those packages being loaded. Additionally, if I've chosen to load the @uqds/form package styles and use encapsulation (e.g. `.uq label { ... }`; as per the package's Sass import configuration), we also have to ensure that the header input styles have stronger specificity than the resulting form styles.

I've had to apply the below style rules to replicate the header's appearance as in the UQDS Stories (incl. overriding the form styles as my header is wrapped in a `div` element with the `.uq` class).
```scss
@use '@uqds/core/src/scss/_global' as core;
@use '@uqds/header/src/scss/_component.scss' as *;

$base-class: 'uq-header';

.#{$base-class} {
    -webkit-font-smoothing: antialiased;
    -moz-osx-font-smoothing: grayscale;

    *, *::before, *::after {
        box-sizing: border-box;
    }

    &__nav-secondary-link {
        text-decoration: none;
        transition: .2s color;

        &:hover {
            text-decoration: underline;
        }
    }

    &__search-query-label {
        // Visually hide
        position: absolute !important;
        overflow: hidden;
        clip: rect(1px, 1px, 1px, 1px);
        width: 1px;
        height: 1px;
        word-wrap: normal;
        margin: 0;
        padding: 0;
    }

    &__search-query-input {
        background-color: core.$uq-white;
        max-width: 100%;
        min-width: 100%;
        border: 1px solid core.$uq-neutral-light40;
        border-radius: 2px;
        font-size: core.$font-size;
        color: core.$text;
        line-height: 1;
        font-family: core.$font-body;
        
        &:focus {
            border-color: core.$link;
            box-shadow: 0 0 0 1px core.$link inset;
            outline: none;
        }
    }

    &__search-query-submit {
        appearance: none;
    }

    &__search-range {
        // CSS overrides to beat the encapsulation form styles specificity
        .#{$base-class}__search-radio[type=radio] {
            border: 1px solid core.$uq-white;

            &:focus {
                border-color: core.$uq-white;
                box-shadow: 0 0 0 1px core.$link;
            }

            &:checked {
                border-color: core.$uq-white;
                border-width: 2px;

                &::after {
                    background-color: core.$uq-white;
                }

                &:focus {
                    border-color: core.$uq-white;
                    box-shadow: 0 0 0 1px core.$link;
                }
            }
        }

        .#{$base-class}__search-label {
            color: core.$uq-white;
            cursor: pointer;
        }
    }

    .megamenu {
        &__overview-link,
        &__menu ul li a {
            text-decoration: none;
            transition: .2s color;

            &:hover {
                text-decoration: underline;
            }
        }
    }
}
```
